# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import clientsvc_pb2 as clientsvc__pb2


class ClientServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterNewClient = channel.unary_unary(
        '/ClientService/RegisterNewClient',
        request_serializer=clientsvc__pb2.NewClientRequest.SerializeToString,
        response_deserializer=clientsvc__pb2.NewClientResponse.FromString,
        )
    self.UnregisterClient = channel.unary_unary(
        '/ClientService/UnregisterClient',
        request_serializer=clientsvc__pb2.UnregisterClientRequest.SerializeToString,
        response_deserializer=clientsvc__pb2.UnregisterClientResponse.FromString,
        )
    self.NewTransactions = channel.unary_unary(
        '/ClientService/NewTransactions',
        request_serializer=clientsvc__pb2.NewTransactionsRequest.SerializeToString,
        response_deserializer=clientsvc__pb2.NewTransactionsResponse.FromString,
        )


class ClientServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RegisterNewClient(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnregisterClient(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NewTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterNewClient': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterNewClient,
          request_deserializer=clientsvc__pb2.NewClientRequest.FromString,
          response_serializer=clientsvc__pb2.NewClientResponse.SerializeToString,
      ),
      'UnregisterClient': grpc.unary_unary_rpc_method_handler(
          servicer.UnregisterClient,
          request_deserializer=clientsvc__pb2.UnregisterClientRequest.FromString,
          response_serializer=clientsvc__pb2.UnregisterClientResponse.SerializeToString,
      ),
      'NewTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.NewTransactions,
          request_deserializer=clientsvc__pb2.NewTransactionsRequest.FromString,
          response_serializer=clientsvc__pb2.NewTransactionsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ClientService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
