# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientsvc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clientsvc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x63lientsvc.proto\"\xcb\x01\n\x10NewClientRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x32\n\tsub_infos\x18\x02 \x03(\x0b\x32\x1f.NewClientRequest.SubInfosEntry\x1a&\n\x07SubInfo\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x1aJ\n\rSubInfosEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.NewClientRequest.SubInfo:\x02\x38\x01\"#\n\x11NewClientResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"*\n\x17UnregisterClientRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"*\n\x18UnregisterClientResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\xc9\x02\n\x16NewTransactionsRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12?\n\x0ctransactions\x18\x02 \x03(\x0b\x32).NewTransactionsRequest.TransactionsEntry\x1a@\n\x0bTransaction\x12\x17\n\x0fraw_transaction\x18\x01 \x01(\x0c\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\x12\n\n\x02to\x18\x03 \x01(\x0c\x1a\x41\n\x0cTransactions\x12\x31\n\x04list\x18\x01 \x03(\x0b\x32#.NewTransactionsRequest.Transaction\x1aY\n\x11TransactionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.NewTransactionsRequest.Transactions:\x02\x38\x01\")\n\x17NewTransactionsResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xe0\x01\n\rClientService\x12<\n\x11RegisterNewClient\x12\x11.NewClientRequest\x1a\x12.NewClientResponse\"\x00\x12I\n\x10UnregisterClient\x12\x18.UnregisterClientRequest\x1a\x19.UnregisterClientResponse\"\x00\x12\x46\n\x0fNewTransactions\x12\x17.NewTransactionsRequest\x1a\x18.NewTransactionsResponse\"\x00\x62\x06proto3'
)




_NEWCLIENTREQUEST_SUBINFO = _descriptor.Descriptor(
  name='SubInfo',
  full_name='NewClientRequest.SubInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='NewClientRequest.SubInfo.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='NewClientRequest.SubInfo.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=147,
)

_NEWCLIENTREQUEST_SUBINFOSENTRY = _descriptor.Descriptor(
  name='SubInfosEntry',
  full_name='NewClientRequest.SubInfosEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='NewClientRequest.SubInfosEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='NewClientRequest.SubInfosEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=223,
)

_NEWCLIENTREQUEST = _descriptor.Descriptor(
  name='NewClientRequest',
  full_name='NewClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='NewClientRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_infos', full_name='NewClientRequest.sub_infos', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NEWCLIENTREQUEST_SUBINFO, _NEWCLIENTREQUEST_SUBINFOSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=223,
)


_NEWCLIENTRESPONSE = _descriptor.Descriptor(
  name='NewClientResponse',
  full_name='NewClientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='NewClientResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=260,
)


_UNREGISTERCLIENTREQUEST = _descriptor.Descriptor(
  name='UnregisterClientRequest',
  full_name='UnregisterClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='UnregisterClientRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=304,
)


_UNREGISTERCLIENTRESPONSE = _descriptor.Descriptor(
  name='UnregisterClientResponse',
  full_name='UnregisterClientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='UnregisterClientResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=348,
)


_NEWTRANSACTIONSREQUEST_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='NewTransactionsRequest.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_transaction', full_name='NewTransactionsRequest.Transaction.raw_transaction', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='NewTransactionsRequest.Transaction.hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='NewTransactionsRequest.Transaction.to', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=522,
)

_NEWTRANSACTIONSREQUEST_TRANSACTIONS = _descriptor.Descriptor(
  name='Transactions',
  full_name='NewTransactionsRequest.Transactions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='NewTransactionsRequest.Transactions.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=589,
)

_NEWTRANSACTIONSREQUEST_TRANSACTIONSENTRY = _descriptor.Descriptor(
  name='TransactionsEntry',
  full_name='NewTransactionsRequest.TransactionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='NewTransactionsRequest.TransactionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='NewTransactionsRequest.TransactionsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=680,
)

_NEWTRANSACTIONSREQUEST = _descriptor.Descriptor(
  name='NewTransactionsRequest',
  full_name='NewTransactionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='NewTransactionsRequest.client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactions', full_name='NewTransactionsRequest.transactions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NEWTRANSACTIONSREQUEST_TRANSACTION, _NEWTRANSACTIONSREQUEST_TRANSACTIONS, _NEWTRANSACTIONSREQUEST_TRANSACTIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=680,
)


_NEWTRANSACTIONSRESPONSE = _descriptor.Descriptor(
  name='NewTransactionsResponse',
  full_name='NewTransactionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='NewTransactionsResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=682,
  serialized_end=723,
)

_NEWCLIENTREQUEST_SUBINFO.containing_type = _NEWCLIENTREQUEST
_NEWCLIENTREQUEST_SUBINFOSENTRY.fields_by_name['value'].message_type = _NEWCLIENTREQUEST_SUBINFO
_NEWCLIENTREQUEST_SUBINFOSENTRY.containing_type = _NEWCLIENTREQUEST
_NEWCLIENTREQUEST.fields_by_name['sub_infos'].message_type = _NEWCLIENTREQUEST_SUBINFOSENTRY
_NEWTRANSACTIONSREQUEST_TRANSACTION.containing_type = _NEWTRANSACTIONSREQUEST
_NEWTRANSACTIONSREQUEST_TRANSACTIONS.fields_by_name['list'].message_type = _NEWTRANSACTIONSREQUEST_TRANSACTION
_NEWTRANSACTIONSREQUEST_TRANSACTIONS.containing_type = _NEWTRANSACTIONSREQUEST
_NEWTRANSACTIONSREQUEST_TRANSACTIONSENTRY.fields_by_name['value'].message_type = _NEWTRANSACTIONSREQUEST_TRANSACTIONS
_NEWTRANSACTIONSREQUEST_TRANSACTIONSENTRY.containing_type = _NEWTRANSACTIONSREQUEST
_NEWTRANSACTIONSREQUEST.fields_by_name['transactions'].message_type = _NEWTRANSACTIONSREQUEST_TRANSACTIONSENTRY
DESCRIPTOR.message_types_by_name['NewClientRequest'] = _NEWCLIENTREQUEST
DESCRIPTOR.message_types_by_name['NewClientResponse'] = _NEWCLIENTRESPONSE
DESCRIPTOR.message_types_by_name['UnregisterClientRequest'] = _UNREGISTERCLIENTREQUEST
DESCRIPTOR.message_types_by_name['UnregisterClientResponse'] = _UNREGISTERCLIENTRESPONSE
DESCRIPTOR.message_types_by_name['NewTransactionsRequest'] = _NEWTRANSACTIONSREQUEST
DESCRIPTOR.message_types_by_name['NewTransactionsResponse'] = _NEWTRANSACTIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewClientRequest = _reflection.GeneratedProtocolMessageType('NewClientRequest', (_message.Message,), {

  'SubInfo' : _reflection.GeneratedProtocolMessageType('SubInfo', (_message.Message,), {
    'DESCRIPTOR' : _NEWCLIENTREQUEST_SUBINFO,
    '__module__' : 'clientsvc_pb2'
    # @@protoc_insertion_point(class_scope:NewClientRequest.SubInfo)
    })
  ,

  'SubInfosEntry' : _reflection.GeneratedProtocolMessageType('SubInfosEntry', (_message.Message,), {
    'DESCRIPTOR' : _NEWCLIENTREQUEST_SUBINFOSENTRY,
    '__module__' : 'clientsvc_pb2'
    # @@protoc_insertion_point(class_scope:NewClientRequest.SubInfosEntry)
    })
  ,
  'DESCRIPTOR' : _NEWCLIENTREQUEST,
  '__module__' : 'clientsvc_pb2'
  # @@protoc_insertion_point(class_scope:NewClientRequest)
  })
_sym_db.RegisterMessage(NewClientRequest)
_sym_db.RegisterMessage(NewClientRequest.SubInfo)
_sym_db.RegisterMessage(NewClientRequest.SubInfosEntry)

NewClientResponse = _reflection.GeneratedProtocolMessageType('NewClientResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWCLIENTRESPONSE,
  '__module__' : 'clientsvc_pb2'
  # @@protoc_insertion_point(class_scope:NewClientResponse)
  })
_sym_db.RegisterMessage(NewClientResponse)

UnregisterClientRequest = _reflection.GeneratedProtocolMessageType('UnregisterClientRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNREGISTERCLIENTREQUEST,
  '__module__' : 'clientsvc_pb2'
  # @@protoc_insertion_point(class_scope:UnregisterClientRequest)
  })
_sym_db.RegisterMessage(UnregisterClientRequest)

UnregisterClientResponse = _reflection.GeneratedProtocolMessageType('UnregisterClientResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNREGISTERCLIENTRESPONSE,
  '__module__' : 'clientsvc_pb2'
  # @@protoc_insertion_point(class_scope:UnregisterClientResponse)
  })
_sym_db.RegisterMessage(UnregisterClientResponse)

NewTransactionsRequest = _reflection.GeneratedProtocolMessageType('NewTransactionsRequest', (_message.Message,), {

  'Transaction' : _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
    'DESCRIPTOR' : _NEWTRANSACTIONSREQUEST_TRANSACTION,
    '__module__' : 'clientsvc_pb2'
    # @@protoc_insertion_point(class_scope:NewTransactionsRequest.Transaction)
    })
  ,

  'Transactions' : _reflection.GeneratedProtocolMessageType('Transactions', (_message.Message,), {
    'DESCRIPTOR' : _NEWTRANSACTIONSREQUEST_TRANSACTIONS,
    '__module__' : 'clientsvc_pb2'
    # @@protoc_insertion_point(class_scope:NewTransactionsRequest.Transactions)
    })
  ,

  'TransactionsEntry' : _reflection.GeneratedProtocolMessageType('TransactionsEntry', (_message.Message,), {
    'DESCRIPTOR' : _NEWTRANSACTIONSREQUEST_TRANSACTIONSENTRY,
    '__module__' : 'clientsvc_pb2'
    # @@protoc_insertion_point(class_scope:NewTransactionsRequest.TransactionsEntry)
    })
  ,
  'DESCRIPTOR' : _NEWTRANSACTIONSREQUEST,
  '__module__' : 'clientsvc_pb2'
  # @@protoc_insertion_point(class_scope:NewTransactionsRequest)
  })
_sym_db.RegisterMessage(NewTransactionsRequest)
_sym_db.RegisterMessage(NewTransactionsRequest.Transaction)
_sym_db.RegisterMessage(NewTransactionsRequest.Transactions)
_sym_db.RegisterMessage(NewTransactionsRequest.TransactionsEntry)

NewTransactionsResponse = _reflection.GeneratedProtocolMessageType('NewTransactionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWTRANSACTIONSRESPONSE,
  '__module__' : 'clientsvc_pb2'
  # @@protoc_insertion_point(class_scope:NewTransactionsResponse)
  })
_sym_db.RegisterMessage(NewTransactionsResponse)


_NEWCLIENTREQUEST_SUBINFOSENTRY._options = None
_NEWTRANSACTIONSREQUEST_TRANSACTIONSENTRY._options = None

_CLIENTSERVICE = _descriptor.ServiceDescriptor(
  name='ClientService',
  full_name='ClientService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=726,
  serialized_end=950,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterNewClient',
    full_name='ClientService.RegisterNewClient',
    index=0,
    containing_service=None,
    input_type=_NEWCLIENTREQUEST,
    output_type=_NEWCLIENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UnregisterClient',
    full_name='ClientService.UnregisterClient',
    index=1,
    containing_service=None,
    input_type=_UNREGISTERCLIENTREQUEST,
    output_type=_UNREGISTERCLIENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NewTransactions',
    full_name='ClientService.NewTransactions',
    index=2,
    containing_service=None,
    input_type=_NEWTRANSACTIONSREQUEST,
    output_type=_NEWTRANSACTIONSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENTSERVICE)

DESCRIPTOR.services_by_name['ClientService'] = _CLIENTSERVICE

# @@protoc_insertion_point(module_scope)
