# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dappcontainer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dappcontainer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13\x64\x61ppcontainer.proto\"\x95\x01\n\x07Receipt\x12\x0e\n\x06txhash\x18\x01 \x01(\x0c\x12\x18\n\x10\x63ontract_address\x18\x02 \x01(\x0c\x12\x0e\n\x06status\x18\x03 \x01(\x04\x12\x1a\n\x04logs\x18\x04 \x03(\x0b\x32\x0c.Receipt.Log\x1a\x34\n\x03Log\x12\x0e\n\x06topics\x18\x01 \x03(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0c\"%\n\x13NewReceiptsResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\x42\n\rDAppContainer\x12\x31\n\x0bNewReceipts\x12\x08.Receipt\x1a\x14.NewReceiptsResponse\"\x00(\x01\x62\x06proto3'
)




_RECEIPT_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='Receipt.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topics', full_name='Receipt.Log.topics', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Receipt.Log.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='Receipt.Log.address', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=173,
)

_RECEIPT = _descriptor.Descriptor(
  name='Receipt',
  full_name='Receipt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txhash', full_name='Receipt.txhash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contract_address', full_name='Receipt.contract_address', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='Receipt.status', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logs', full_name='Receipt.logs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RECEIPT_LOG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=173,
)


_NEWRECEIPTSRESPONSE = _descriptor.Descriptor(
  name='NewReceiptsResponse',
  full_name='NewReceiptsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='NewReceiptsResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=212,
)

_RECEIPT_LOG.containing_type = _RECEIPT
_RECEIPT.fields_by_name['logs'].message_type = _RECEIPT_LOG
DESCRIPTOR.message_types_by_name['Receipt'] = _RECEIPT
DESCRIPTOR.message_types_by_name['NewReceiptsResponse'] = _NEWRECEIPTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Receipt = _reflection.GeneratedProtocolMessageType('Receipt', (_message.Message,), {

  'Log' : _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), {
    'DESCRIPTOR' : _RECEIPT_LOG,
    '__module__' : 'dappcontainer_pb2'
    # @@protoc_insertion_point(class_scope:Receipt.Log)
    })
  ,
  'DESCRIPTOR' : _RECEIPT,
  '__module__' : 'dappcontainer_pb2'
  # @@protoc_insertion_point(class_scope:Receipt)
  })
_sym_db.RegisterMessage(Receipt)
_sym_db.RegisterMessage(Receipt.Log)

NewReceiptsResponse = _reflection.GeneratedProtocolMessageType('NewReceiptsResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWRECEIPTSRESPONSE,
  '__module__' : 'dappcontainer_pb2'
  # @@protoc_insertion_point(class_scope:NewReceiptsResponse)
  })
_sym_db.RegisterMessage(NewReceiptsResponse)



_DAPPCONTAINER = _descriptor.ServiceDescriptor(
  name='DAppContainer',
  full_name='DAppContainer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=214,
  serialized_end=280,
  methods=[
  _descriptor.MethodDescriptor(
    name='NewReceipts',
    full_name='DAppContainer.NewReceipts',
    index=0,
    containing_service=None,
    input_type=_RECEIPT,
    output_type=_NEWRECEIPTSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DAPPCONTAINER)

DESCRIPTOR.services_by_name['DAppContainer'] = _DAPPCONTAINER

# @@protoc_insertion_point(module_scope)
