# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dappcontainer_pb2 as dappcontainer__pb2


class DAppContainerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.NewReceipts = channel.stream_unary(
        '/DAppContainer/NewReceipts',
        request_serializer=dappcontainer__pb2.Receipt.SerializeToString,
        response_deserializer=dappcontainer__pb2.NewReceiptsResponse.FromString,
        )


class DAppContainerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def NewReceipts(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DAppContainerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'NewReceipts': grpc.stream_unary_rpc_method_handler(
          servicer.NewReceipts,
          request_deserializer=dappcontainer__pb2.Receipt.FromString,
          response_serializer=dappcontainer__pb2.NewReceiptsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DAppContainer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
